### ISSUE TITLE
Review MVR checklist

### ISSUE THREAD

**Issue by eigenhombre** [eigenhombre/cl-oju#10]
From https://gist.github.com/eigenhombre/204400c786f9dba3a8d3193d3ce1542a:
- [x] LICENSE file
- [x] Automated build via Docker and GitHub Actions
- [x] Build badge
- [x] Artwork
- [x] Versioned
- [x] Minimum snippet / example
- [x] Link to API and/or `help` output
- [x] Project available in public package manager (want Quicklisp, issue filed there; but, Ultralisp works)
- [x] Track outstanding TODOs in Issues

**Comment by eigenhombre** [comment]
Issue for inclusion submitted to Quicklisp: https://github.com/quicklisp/quicklisp-projects/issues/2183

**Comment by eigenhombre** [comment]
Added to quicklisp today!
